package by.htp.jd2.command;

/**
 * @author alexey
 * enum of all commands
 */
public enum CommandName {

    AUTHORIZATION,
    NO_SUCH_COMMAND,
    REGISTRATION,
    LOG_OUT,
    USER_PAGE,
    ORDER_PAGE,
    ALL_USERS,
    ADD_CAR,
    ADD_CAR_PAGE,
    DEL_CAR,
    DEL_USER,
    CONTROL_CAR_PAGE,
    CRASH_PAGE_ADMIN,
    ORDER_PAGE_USER,
    ORDER_PAGE_STEP2_USER,
    ORDER_PAGE_STEP3_USER,
    USER_ORDERS_PAGE,
    CONFIRM_ORDER,
    PAY,
    NEW_CRASH_ORDER_PAGE,
    ACTIVATE_USER,
    ACTIVATE_CAR,
    ADD_MONEY,
    COMPLETE_ORDER,
    CANCEL_ORDER,
    SET_LANGUAGE,
    ADD_CRASH,
    USER_CRASH_PAGE,
    USER_CRASH_PAY,
    GET_TRANSMISSION_CARS,
    GET_FUEL_CARS,
    USER_ADD_FUNDS_PAGE,
    USER_ADD_MONEY,
    USER_SEARCH,
    USER_ORDERS_SEARCH




}
